[fix] 자동 배포 스크립트 변경 -> sleep(10)이 아닌 요청 후 200 시 다음으로 넘어감.

diff --git a/.github/workflows/jwt-actions.yml b/.github/workflows/jwt-actions.yml
--- a/.github/workflows/jwt-actions.yml
+++ b/.github/workflows/jwt-actions.yml
@@ -104,7 +104,18 @@ jobs:
             docker pull ghcr.io/${{ github.repository_owner }}/green:1.0
             docker run -d -p 3001:3000 --name green ghcr.io/${{ github.repository_owner }}/green:1.0
 
-            sleep 10
+            for i in {i..60}; do
+              if curl -sf http://localhost:3001/health > /dev/null; then
+                echo "Green container is ready"
+                break
+              fi
+                echo "Waiting for green container (attempt $i)..."
+                sleep 1
+                if [ $i -eq 60]; then
+                  echo "Green container failed to start in time"
+                  exit 1
+                fi
+            done
 
             sudo touch /etc/nginx/green.flag
             sudo rm /etc/nginx/blue.flag
@@ -117,6 +128,20 @@ jobs:
             docker run -d -p 3002:3000 --name blue ghcr.io/${{ github.repository_owner }}/blue:1.0
 
             sleep 10
+
+            for i in {i..60}; do
+              if curl -sf http://localhost:3002/health > /dev/null; then
+                echo "Blue container is ready!"
+                break
+              fi
+              echo "Waiting for blue container (attempt $i)..."
+              sleep 1
+              if [ $i -eq 60]; then
+                echo "Blue container failed to start in time."
+                exit 1
+              fi
+            done
+
 
             sudo touch /etc/nginx/blue.flag
             sudo rm /etc/nginx/green.flag
